[2025-04-23T19:24:46.549+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T19:24:46.561+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_etl_dbt_pipeline.run_dbt_transformations scheduled__2025-04-22T00:00:00+00:00 [queued]>
[2025-04-23T19:24:46.567+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_etl_dbt_pipeline.run_dbt_transformations scheduled__2025-04-22T00:00:00+00:00 [queued]>
[2025-04-23T19:24:46.567+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-04-23T19:24:46.575+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_transformations> on 2025-04-22 00:00:00+00:00
[2025-04-23T19:24:46.583+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'full_etl_dbt_pipeline', 'run_dbt_transformations', 'scheduled__2025-04-22T00:00:00+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_pipeline.py', '--cfg-path', '/tmp/tmp8_88an16']
[2025-04-23T19:24:46.588+0000] {standard_task_runner.py:105} INFO - Job 243: Subtask run_dbt_transformations
[2025-04-23T19:24:46.587+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2277) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T19:24:46.588+0000] {standard_task_runner.py:72} INFO - Started process 2280 to run task
[2025-04-23T19:24:46.627+0000] {task_command.py:467} INFO - Running <TaskInstance: full_etl_dbt_pipeline.run_dbt_transformations scheduled__2025-04-22T00:00:00+00:00 [running]> on host aab73994fc52
[2025-04-23T19:24:46.686+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_etl_dbt_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T00:00:00+00:00'
[2025-04-23T19:24:46.687+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T19:24:46.689+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-23T19:24:46.690+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'export PATH="$PATH:/home/***/.local/bin" && cd "$DBT_PROJECT_DIR" && dbt run --profiles-dir "$DBT_PROJECT_DIR/config" && dbt test --profiles-dir "$DBT_PROJECT_DIR/config" && dbt snapshot --profiles-dir "$DBT_PROJECT_DIR/config"']
[2025-04-23T19:24:46.697+0000] {subprocess.py:86} INFO - Output:
[2025-04-23T19:24:46.724+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:24:46.724+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:24:46.801+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:24:46.802+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:24:46.802+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:24:46.802+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:24:46.803+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:24:46.803+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:24:46.803+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:24:46.804+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:24:46.804+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:24:46.804+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:24:46.805+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:24:46.805+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:24:46.805+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:24:46.805+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:24:46.805+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:24:46.806+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:24:48.731+0000] {subprocess.py:93} INFO - [0m19:24:48  Running with dbt=1.9.4
[2025-04-23T19:24:49.578+0000] {subprocess.py:93} INFO - [0m19:24:49  Registered adapter: snowflake=1.9.2
[2025-04-23T19:24:49.626+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:24:49.627+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:24:49.759+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:24:49.760+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:24:49.761+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:24:49.761+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:24:49.762+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:24:49.762+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:24:49.763+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:24:49.764+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:24:49.766+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:24:49.769+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:24:49.771+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:24:49.773+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:24:49.773+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:24:49.774+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:24:49.774+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:24:49.774+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:24:50.359+0000] {subprocess.py:93} INFO - [0m19:24:50  Encountered an error:
[2025-04-23T19:24:50.360+0000] {subprocess.py:93} INFO - Compilation Error
[2025-04-23T19:24:50.360+0000] {subprocess.py:93} INFO -   Snapshot 'snapshot.stock_analysis_project.stock_snapshot' (snapshots/stock_snapshot.sql) depends on a node named 'rawstock_data' which was not found
[2025-04-23T19:24:51.142+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-23T19:24:51.151+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-23T19:24:51.155+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=full_etl_dbt_pipeline, task_id=run_dbt_transformations, run_id=scheduled__2025-04-22T00:00:00+00:00, execution_date=20250422T000000, start_date=20250423T192446, end_date=20250423T192451
[2025-04-23T19:24:51.164+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T19:24:51.165+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 243 for task run_dbt_transformations (Bash command failed. The command returned a non-zero exit code 2.; 2280)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-23T19:24:51.210+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-23T19:24:51.221+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T19:24:51.222+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
