[2025-04-24T05:28:47.015+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T05:28:47.025+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_etl_dbt_pipeline.run_dbt_transformations scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T05:28:47.031+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_etl_dbt_pipeline.run_dbt_transformations scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T05:28:47.031+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-04-24T05:28:47.039+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_transformations> on 2025-04-23 00:00:00+00:00
[2025-04-24T05:28:47.047+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'full_etl_dbt_pipeline', 'run_dbt_transformations', 'scheduled__2025-04-23T00:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_pipeline.py', '--cfg-path', '/tmp/tmpepdkqzq3']
[2025-04-24T05:28:47.051+0000] {standard_task_runner.py:105} INFO - Job 266: Subtask run_dbt_transformations
[2025-04-24T05:28:47.050+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1936) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T05:28:47.051+0000] {standard_task_runner.py:72} INFO - Started process 1939 to run task
[2025-04-24T05:28:47.085+0000] {task_command.py:467} INFO - Running <TaskInstance: full_etl_dbt_pipeline.run_dbt_transformations scheduled__2025-04-23T00:00:00+00:00 [running]> on host aab73994fc52
[2025-04-24T05:28:47.145+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_etl_dbt_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:00:00+00:00'
[2025-04-24T05:28:47.146+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T05:28:47.148+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T05:28:47.148+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'export PATH="$PATH:/home/***/.local/bin" && cd "$DBT_PROJECT_DIR" && dbt run --profiles-dir "$DBT_PROJECT_DIR/config" && dbt test --profiles-dir "$DBT_PROJECT_DIR/config" && dbt snapshot --profiles-dir "$DBT_PROJECT_DIR/config"']
[2025-04-24T05:28:47.156+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T05:28:47.464+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-24T05:28:47.465+0000] {subprocess.py:93} INFO -   File "/home/***/.local/bin/dbt", line 5, in <module>
[2025-04-24T05:28:47.465+0000] {subprocess.py:93} INFO -     from dbt.cli.main import cli
[2025-04-24T05:28:47.465+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/__init__.py", line 1, in <module>
[2025-04-24T05:28:47.466+0000] {subprocess.py:93} INFO -     from .main import cli as dbt_cli  # noqa
[2025-04-24T05:28:47.466+0000] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-24T05:28:47.466+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/main.py", line 11, in <module>
[2025-04-24T05:28:47.466+0000] {subprocess.py:93} INFO -     from dbt.adapters.factory import register_adapter
[2025-04-24T05:28:47.467+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/adapters/factory.py", line 9, in <module>
[2025-04-24T05:28:47.467+0000] {subprocess.py:93} INFO -     from dbt_common.events.functions import fire_event
[2025-04-24T05:28:47.467+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt_common/events/__init__.py", line 1, in <module>
[2025-04-24T05:28:47.467+0000] {subprocess.py:93} INFO -     from dbt_common.events.base_types import EventLevel
[2025-04-24T05:28:47.468+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt_common/events/base_types.py", line 4, in <module>
[2025-04-24T05:28:47.468+0000] {subprocess.py:93} INFO -     from dbt_common.events import types_pb2
[2025-04-24T05:28:47.468+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt_common/events/types_pb2.py", line 9, in <module>
[2025-04-24T05:28:47.468+0000] {subprocess.py:93} INFO -     from google.protobuf import runtime_version as _runtime_version
[2025-04-24T05:28:47.468+0000] {subprocess.py:93} INFO - ImportError: cannot import name 'runtime_version' from 'google.protobuf' (/home/***/.local/lib/python3.12/site-packages/google/protobuf/__init__.py)
[2025-04-24T05:28:47.478+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-24T05:28:47.487+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T05:28:47.490+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=full_etl_dbt_pipeline, task_id=run_dbt_transformations, run_id=scheduled__2025-04-23T00:00:00+00:00, execution_date=20250423T000000, start_date=20250424T052847, end_date=20250424T052847
[2025-04-24T05:28:47.499+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T05:28:47.500+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 266 for task run_dbt_transformations (Bash command failed. The command returned a non-zero exit code 1.; 1939)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T05:28:47.527+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T05:28:47.538+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T05:28:47.539+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
